function makeArrayAlpha(selectLength = 0){
    const myArray = [];
    for (let i = 0; i < selectLength; i++){
        if (i == 26){
            console.log("i'm out of letters, sorry!");
            break;
        }
        else{
            let letter = String.fromCharCode(65 + i)
            myArray.push(letter);
        }
    }
    return myArray;
}

let test = [];
let array1 = [];
let array2 = [];

array1 = makeArrayAlpha(3); //console.log(array1);

// // The forEach function can takes 3 args, name, index of and the array itself, the latter one displaying
// // literally an array generated by the forEach; 
// // "Default" mode;
// array1.forEach(function(name, index, array){
//     console.log(`${index}) ${name}`);
//     console.log(array);
// })

// // "Compact" mode;
// array1.forEach(array = (name, index) => {console.log(index, name)})
// array1.forEach(name => console.log(name));

// 
Array.prototype.myForEach = function(functionToCall){
    for (let i = 0; i < this.length; i++){
        functionToCall(this[i], i, this);
    }
}

array1.myForEach(function(name, index, array){
    console.log(`${index}) ${name}`);
    console.log(array)
})